package net.besttoolbars.rakuten.response

import com.fasterxml.jackson.annotation.JsonProperty

data class RakutenTransactionEvent(
    /**
     * The unique ID associated with the Transaction
     */
    @JsonProperty( "etransaction_id")
    val etransactionId: String? = null,

    /**
     * The unique ID associated with the Advertiser
     */
    @JsonProperty( "advertiser_id")
    val advertiserId: String? = null,

    /**
     * Specific Publisher ID
     */
    @JsonProperty( "sid")
    val sid: String? = null,

    /**
     * The Advertiser’s ID for the order
     */
    @JsonProperty( "order_id")
    val orderId: String? = null,

    /**
     * The Offer ID associated with the offer
     * that the transaction was commissioned on
     */
    @JsonProperty( "offer_id")
    val offerId: String? = null,

    /**
     * SKU for the Item
     */
    @JsonProperty( "sku_number")
    val skuNumber: String? = null,

    /**
     * The amount that consumer paid for this item in the Order
     */
    @JsonProperty( "sale_amount")
    val saleAmount: Double? = null,

    /**
     * The quantity of the Items purchased
     */
    @JsonProperty( "quantity")
    val quantity: Long? = null,

    /**
     * The total base commission generated by this transaction
     */
    @JsonProperty( "commissions")
    val commissions: Double? = null,

    /**
     * The date and time when the Order was placed on the Advertisers site
     */
    @JsonProperty( "transaction_date")
    val transactionDate: String? = null,

    /**
     * The date and time when this transaction was processed by Rakuten Marketing
     */
    @JsonProperty( "process_date")
    val processDate: String? = null,

    /**
     * The Transaction is Realtime or Batch
     */
    @JsonProperty( "transaction_type")
    val transactionType: String? = null,

    /**
     * The Product Name of the item purchased or returned
     */
    @JsonProperty( "product_name")
    val productName: String? = null,

    /**
     * Click that the transaction originated from
     */
    @JsonProperty( "u1")
    val u1: String? = null,

    /**
     * The currency of the sale amount for the transaction
     */
    @JsonProperty( "currency")
    val currency: String? = null,

    /**
     * The reported entity is an Event or Transaction
     */
    @JsonProperty( "is_event")
    val isEvent: String? = null,

    @JsonProperty("commission_list_id")
    val commissionListId: String? = null
)